<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gtd"
 *
 * Auto generated by Extension Builder 2016-04-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Getting Things Done',
    'description' => 'Your Todo-List for Getting Things Done',
    'category' => 'plugin',
    'author' => 'Thomas Woehlke',
    'author_email' => 'thomas@woehlke.org',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '0.0.3',
    'constraints' => [
        'depends' => [
            'felogin' => '7.6.0-7.99.99',
            'extbase' => '7.6.0-7.99.99',
            'fluid' => '7.6.0-7.99.99',
            'typo3' => '7.6.0-7.99.99',
            'php' => '5.6.0-7.99.99',
        ],
        'conflicts' => [],
        'suggests' => [
            't3sbootstrap' => '3.1.0-3.1.99',
            'fluid_styled_content' => '7.6.0-7.99.99',
        ],
    ],
];
