<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tw_simpleworklist"
 *
 * Auto generated by Extension Builder 2016-04-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SimpleWorklist',
    'description' => 'Your Todo-List for Getting Things Done',
    'category' => 'plugin',
    'author' => 'Thomas Woehlke',
    'author_email' => 'woehlke@faktura-berlin.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
